application: flat-land
version: master
runtime: python27
api_version: 1
threadsafe: true

## Turn on and off modules or add your own by modifying the includes
## Make sure one of the tailbone/static includes are at the end
## Usually easiest to add your specific includes to the begining of the includes list

includes:
  ## Base includes, authentication, and combined /tailbone.js file
  - tailbone
  ## Qunit tests (only works when running locally)
  - tailbone/test
  ## Get the user location
  # - tailbone/geoip
  ## Full text search must provide a searchable.json at the root level
  # - tailbone/search
  ## Storing and fetching files with the blobstore api
  # - tailbone/files
  ## Read access to any of your cloud storage objects.
  # - tailbone/cloudstore
  ## Simple reverse proxy sometimes useful for cors purposes (note: don't use if you don't have to it
  ## will cost you bandwidth and has no auth you can domain restrict in appengine_config.py)
  # - tailbone/proxy
  ## Clocksync simple synchronization of clocks
  # - tailbone/clocksync
  ## Websocket+WebRTC based mesh server with rooms and load balancing
  # - tailbone/mesh
  ## Load balanced stand alone turn server service
  # - tailbone/turn
  ## Run custom load balanced server on compute engine {eg node.js websocket server}
  # - tailbone/customce
  ## Order in this list is important for restful and pathrewrite, they must be last.
  ## Restful resources
  - tailbone/restful
  ## Any path without a file extension not in /api gets the app/client/index.html text. Useful for
  ## html5 applications that use the history api to write their paths.
  # - tailbone/pathrewrite
  ## Serve the app folder. Static protected resource can change protection in appengine_config.py
  - tailbone/static/protected
  ## Serve the app folder. Static public resource (can only have protected or public not both)
  # - tailbone/static/public


## Don't edit below this line unless before reading about https://developers.google.com/appengine/docs/python/config/appconfig

builtins:
  - appstats: on
  - deferred: on
  - admin_redirect: on
  - remote_api: on

inbound_services:
  - warmup
  - channel_presence

skip_files:
  - ^(.*/)?index\.yaml
  - ^(.*/)?index\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^client/tailbone/.*

pagespeed:
  # domains_to_rewrite:
  # - slowdomain.com
  # url_blacklist:
  # - http://myapp.com/dontoptomize/*
  enabled_rewriters:
  - MinifyCss
  disabled_rewriters:
  - LazyloadImages
  # Available rewriters
  # - ProxyCss # - default
  # - ProxyImages # - default
  # - ProxyJs # - default
  # - ConvertMetaTags # - default
  # - InlineCss # - default
  # - InlineJs
  # - InlineImages
  # - InlinePreviewImages # - default
  # - CollapseWhitespace
  # - CombineHeads
  # - ElideAttributes
  # - RemoveComments
  # - RemoveQuotes
  # - LeftTrimUrls

  # - CombineCss # - default
  # - MoveCssToHead # - default
  # - MinifyCss

  # - WebpOptimization # - default
  # - ImageConvertToJpeg # - default
  # - ImageRecompressJpeg # - default
  # - ImageProgressiveJpeg # - default
  # - ImageRecompressPng # - default
  # - ImageStripMetadata # - default
  # - ImageStripColorProfile # - default
  # - ImageResize # - default
  # - LazyloadImages # - default
  # - ImageAddDimensions

  # - CombineJs # - default
  # - JsOptimize # - default
  # - DeferJs

